//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LinkValue { get; set; }
        public Nullable<int> NumberOfRatings { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public int IdCategory { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
