//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Enlaces = new HashSet<Enlaces>();
        }
    
        public int Id { get; set; }
        public string NombreCategoria { get; set; }
    
        public virtual ICollection<Enlaces> Enlaces { get; set; }
    }
}
