//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnlacesDataBaseEntities : DbContext
    {
        public EnlacesDataBaseEntities()
            : base("name=EnlacesDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categorias> Categorias { get; set; }
        public DbSet<Enlaces> Enlaces { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
